# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dotnetapi-test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io//
        username: ${{ secrets.AzureAppService_ContainerUsername_c30fd9ee73c8411fae8a0cb91744215a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2bd4aed9334e4bdfaa98701a8efa213b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io//${{ secrets.AzureAppService_ContainerUsername_c30fd9ee73c8411fae8a0cb91744215a }}/colac/dotnet-api/dev-2497190398-1:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dotnetapi-test'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ff40e5a209994775a636c0fa0ab4fdc9 }}
        images: 'ghcr.io//${{ secrets.AzureAppService_ContainerUsername_c30fd9ee73c8411fae8a0cb91744215a }}/colac/dotnet-api/dev-2497190398-1:${{ github.sha }}'